### PR TITLE
Load data

### PR DESCRIPTION
**Pull request by jburel**
This PR modifies the way the table is loaded.
We use the CSV available in the repository instead of the loading the table.
This will speed up the notebook

cc @pwalczysko @francesw

### CODE REVIEW

**Comment by pwalczysko** [comment]
Load csv notebook

Works fine, but there is a problem with compound name.   Only numbers are in the csv produced by the notebook
, not names, see screeshot 
Screenshot 2021-05-14 at 14 19 49

**Comment by pwalczysko** [comment]
the  "loadtable" notebook does not have the problem with compound names described for the other notebook which loads the csv https://github.com/IDR/idr0094-ellinger-sarscov2/pull/5#issuecomment-841245724

**Comment by jburel** [comment]
@pwalczysko the problem should now be fixed

**Comment by pwalczysko** [comment]
Works as expected. REady to merge fmpov

**Comment by sbesson** [comment]
Speeding up the notebook execution in the context of the OME2021 workshop makes sense as a short-term solution.

Separately, has there been some profiling of the table access when using the API? Or is the performance issue known and captured elsewhere?

**Comment by jburel** [comment]
This is a temporary solution until we fix the issues. Otherwise the "IDR" experience will not be great.
The same problem exists with idr0093

We have 2 problems
* Loading large tables takes a good amount of time regardless of the programming languages. We will need to consider the loading in "chunks"  (similar to what is done in web). I have not done some profiling due to time constraint
* The fact that we cannot query per column is a second problem.

I need to capture that on the metadata as previously discussed.

**Comment by jburel** [comment]
* https://github.com/ome/omero-metadata/issues/57
* https://github.com/ome/rOMERO-gateway/issues/93

**Pull request merged**
