### PR TITLE
Apps

### PR DESCRIPTION
**Pull request by jburel**
Adds shiny app.
The link in the notebook and the README won't work until this PR is merged
To test the link use
https://binder.bioimagearchive.org/v2/gh/jburel/idr0094-ellinger-sarscov2/apps?urlpath=shiny/apps/

cc @pwalczysko @francesw

### CODE REVIEW

**Comment by pwalczysko** [comment]
This is much cleaner now, the curves and description makes sense.
I have just two problems:

1. the curve for Remdesivir is not fitting well into the graph window (see screenshot below), this does not happen for other compounds I tried 

Screenshot 2021-05-20 at 14 36 14


2. When filtering for a compound using the textbox above dropdown menu, a red error is highlighted (see screenshot)
Screenshot 2021-05-20 at 14 36 31

**Comment by jburel** [comment]
@pwalczysko thanks for spotting that.
 I have now fixed both issues if you want to try again

**Comment by pwalczysko** [comment]
> @pwalczysko thanks for spotting that.
> I have now fixed both issues if you want to try again

Yes, this is fixed. But see the screenshot below. The Remdesivir  curve was "leaking" over the top of the graph, but the one shown below is leaking out of the bottom line of the graph. Sorry for not noticing the first time.


Screenshot 2021-05-20 at 18 09 47

**Comment by jburel** [comment]
I have increased the interval so it should now work.

**Comment by pwalczysko** [comment]
Looks good, thank you. Ready to merge fmpov.

**Comment by jburel** [comment]
Thanks @pwalczysko

**Pull request merged**
