### PR TITLE
Fix trailing whitespaces and comma in idr0094-screenA-annotation.csv

### LINKED ISSUE #14: Fix leading/trailing whitespace in Key-Value pairs
Find values under 'Compound' that have a trailing whitespace:

```
[wmoore@prod111-omeroreadwrite ~]$ /opt/omero/server/OMERO.server/bin/omero hql "select mv.value from MapAnnotation m join m.mapValue as mv where mv.value like '% ' and m.ns='openmicroscopy.org/mapr/compound'"
Server: [localhost:4064]
Username: [wmoore]demo
Password:
Created session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
 #  | Col1                                     
----+------------------------------------------
 0  | AG-1024                                  
 1  | EHop-016                                 
 2  | Dovitinib Dilactic Acid                  
 3  | BMS-582949                               
 4  | Tyrphostin 9                             
 5  | VX-11e                                   
 6  | Olmutinib                                
 7  | PKC-412 (Midostaurin)                    
 8  | Indinavir                                
 9  | Chlorcyclizine hydrochloride             
 10 | CX-6258 HCl                              
 11 | Plicamycin (Mithramycin)                 
 12 | PFI-1(PF-6405761)                        
 13 | Geranyl-farnesylacetate,                 
 14 | Pramipexole dihydrochloride monohydrate  
 15 | Golvatinib (E7050)                       
 16 | Vanillin                                 
 17 | PIK-75                                   
 18 | 4,2,4'-Tribenzyloxy-6'-hydroxychalcone   
 19 | GZD824 Dimesylate                        
 20 | Roscovitine (Seliciclib, CYC202)         
 21 | PF-299804                                
(22 rows)
```

E.g. for `AG-1024` searching with `contains` finds 9 images in idr0094 that are not found when searching with `equals`:
https://idr.openmicroscopy.org/search/?key=Compound+Name&value=ag-1024&operator=contains

Other values in idr0094:  (other values in idr064A and idr0088)
```
AG-1024
PKC-412 (Midostaurin)
Indinavir
Chlorcyclizine hydrochloride
Plicamycin (Mithramycin)
PFI-1(PF-6405761)
Geranyl-farnesylacetate,  - includes comma!
Pramipexole dihydrochloride monohydrate
Golvatinib (E7050)
Vanillin
PIK-75 
GZD824 Dimesylate
Roscovitine (Seliciclib, CYC202)
```

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #14. 

This fixes the various compound names found to have trailing whitespace (or an extra comma) at the issue above.

### CODE REVIEW

**Comment by will-moore** [comment]
I noticed while searching the csv for ` ,` that this occurs in other places where it maybe isn't intended, within long names like

`[4-[(5S,5aR,8aR,9R)-5-[[(2R,4aR,6R,7R,8R,8aS)-7,8-dihydroxy-2-methyl-4,4a,6,7,8,8a-hexahydropyrano[3,2-d][1,3]dioxin-6-yl]oxy]-8-oxo-5a,6,8a,9-tetrahydro-5H-isobenzofuro[6,5-f][1,3]benzodioxol-9-yl]-2  ,6-dimethoxy-phenyl] dihydrogen phosphate`

Here, the `2  ,6` looks like it shouldn't have whitespace, to be consistent with the rest of the name?

There are 8 examples of this in that csv file.
Should I fix them as part of this PR?

cc @sbesson @francesw

**Comment by francesw** [comment]
yes, that would be good, thanks

**Comment by will-moore** [comment]
On idr-testing...

```
$ omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/organism", "openmicroscopy.org/mapr/antibody", "openmicroscopy.org/mapr/gene", "openmicroscopy.org/mapr/cell_line", "openmicroscopy.org/mapr/phenotype", "openmicroscopy.org/mapr/sirna", "openmicroscopy.org/mapr/compound", "openmicroscopy.org/mapr/protein"], "typesToIgnore":["Annotation"]}' --cfg screenA/idr0094-screenA-bulkmap-config.yml Screen:2602

$ omero metadata populate --context deletemap --report --wait 300 --batch 100 --cfg screenA/idr0094-screenA-bulkmap-config.yml Screen:2602

$ python /uod/idr/metadata/idr-utils/scripts/annotate/clean_orphaned_maps.py

$ omero delete Annotation:35820013 --report

$ omero metadata populate --report --batch 1000 --file screenA/idr0094-screenA-annotation.csv Screen:2602

$ omero metadata populate --context bulkmap --batch 100 --cfg screenA/idr0094-screenA-bulkmap-config.yml Screen:2602
ERROR:omero_metadata.populate:Missing primary keys (Continuing): Missing primary key fields: {'Compound Name URL'} [('Compound Name', ['Dihydrotachysterol']), ('Compound Name URL', [])] 
ERROR:omero_metadata.populate:Missing primary keys (Continuing): Missing primary key fields: {'Compound Name URL'} [('Compound Name', ['JNJ-16259685']), ('Compound Name URL', [])] 
ERROR:omero_metadata.populate:Missing primary keys (Continuing): Missing primary key fields: {'Compound Name URL'} [('Compound Name', ['SNAP']), ('Compound Name URL', [])] 
```

Checking KVP from an example image, e.g. http://localhost:9000/webclient/api/annotations/?type=map&image=10552535 shows that value `"AG-1024"` no-longer has trailing whitespace.

The ERRORs (for 238 compounds) are warning of missing `Compound Name URL` but that is also missing on production idr (no change).

**Comment by will-moore** [comment]
For ScreenB this was a fix in only a single Map Annotation.
Updated manually then removed and replaced the OMERO.table:

```
$ omero obj map-set MapAnnotation:27269601 mapValue "Compound Name" "PIK-75"

$ omero delete Annotation:27265812 --report
$ omero metadata populate --report --batch 1000 --file screenB/idr0094-screenB-annotation.csv Screen:2603
```

**Comment by will-moore** [comment]
NB: for ScreenA it might be easier to only delete the Compound KVPs as described at https://github.com/IDR/SubmissionWorkflow/blob/master/import.md#delete-one-or-a-few-mapr-categories
with namespaces for `openmicroscopy.org/mapr/compound` and `openmicroscopy.org/mapr/compound/supplementary` (for SMILES fixes)

**Comment by will-moore** [comment]
Frances "ok, all good with idr0094 on localhost 9000" (idr-testing). Will now apply to idr-next...

**Comment by will-moore** [comment]
idr-next: checked-out this PR branch, then:

```
(venv3) [wmoore@prod111-omeroreadwrite idr0094-ellinger-sarscov2]$ omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound", "openmicroscopy.org/mapr/compound/supplementary"], "typesToIgnore":["Annotation"]}' --cfg screenA/idr0094-screenA-bulkmap-config.yml Screen:2602

omero metadata deletebulkanns Screen:2602

omero metadata populate --report --batch 1000 --file screenA/idr0094-screenA-annotation.csv Screen:2602

omero metadata populate --context bulkmap --batch 100 --cfg screenA/idr0094-screenA-bulkmap-config.yml --localcfg '{"ns":["openmicroscopy.org/mapr/compound", "openmicroscopy.org/mapr/compound/supplementary"]}' Screen:2602
```

and screen B - didn't need to fix the MapAnnotation value PIK-75 as this has already been fixed.
Just updated the table:

```
omero metadata deletebulkanns Screen:2603
omero metadata populate --report --batch 1000 --file screenB/idr0094-screenB-annotation.csv Screen:2603
```

**Comment by dominikl** [comment]
In order to fix the problem with the duplicated compound map annotation I removed all the compound map annotation from idr0094 and idr0088, ran the clean up script and re-annotated both datasets. Idr0088 still running, I have to remove the empty map annotation (created by idr0094 annotation) afterwards with: `omero hql "select m from MapAnnotation m join m.mapValue mv join m.mapValue mv2 where m.ns='openmicroscopy.org/mapr/compound' and mv.name='Compound Name' and mv.value='' and mv2.name='Compound Name URL' and mv2.value=''"` + `omero delete ...`

Commands for reannotation used:
```
omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0088-screenA-bulkmap-config.yml Screen:2651

omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0094-screenA-bulkmap-config.yml Screen:2602

omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0094-screenB-bulkmap-config.yml Screen:2603

python /uod/idr/metadata/idr-utils/scripts/annotate/clean_orphaned_maps.py

# INFO:root:Found 18561 orphaned Compound maps

omero metadata populate --context bulkmap --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0094-screenA-bulkmap-config.yml Screen:2602 

omero metadata populate --context bulkmap --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0094-screenB-bulkmap-config.yml Screen:2603

omero metadata populate --context bulkmap --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg idr0088-screenA-bulkmap-config.yml Screen:2651
```

@will-moore  Could you add the `omitempty: no` argument for compound to the bulkmap configs, that's needed because there are empty entries in the annotation csv.
```
  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Compound Name
          clientname: Compound Name
          include: yes
          omitempty: no
        - name: Compound PubChem URL
          clientname: Compound Name URL
          include: yes
          omitempty: no
```

**Comment by will-moore** [comment]
Thanks @dominikl - like that 6cfcca4 ?

**Comment by will-moore** [comment]
I think these changes are all released now - good to merge this PR?

**Pull request merged**
