### PR TITLE
Web api

### PR DESCRIPTION
**Pull request by jburel**
* Use the web api to load the data in notebook
* Display one thumbnail per concentration and per well for the data associated to a given compound
* Use the web api to load data in the shiny app.
cc @pwalczysko  @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good, works nicely 👍 Just one potential improvement, although not really related to this PR: You could wrap the options for the drop down list into a `sort`, otherwise the order of the entries is more or less random, ie. line 60 `selectInput("compound", h4("Select Compound"), choices = sort(cn), selected = "Remdesivir")`

**Comment by pwalczysko** [comment]
> Looks good, works nicely 👍 Just one potential improvement, although not really related to this PR: You could wrap the options for the drop down list into a `sort`, otherwise the order of the entries is more or less random, ie. line 60 `selectInput("compound", h4("Select Compound"), choices = sort(cn), selected = "Remdesivir")`

@dominikl agreed. I was using the search function (the box above the dropdown is editable(

**Comment by pwalczysko** [comment]
Problem with Compound name display in the Filter by compound cell
Numbers discplayed only. Also, the concentration has no units.
Screenshot 2021-05-24 at 11 18 55

**Comment by pwalczysko** [comment]
The images are very nice

Screenshot 2021-05-24 at 11 21 50

2 RFEs here:
1. bigger text font on the concentraion numbers above the images
2. print out which compound is being displayed (not on every image, just on the top is enough, I had to study the cells above quite hard to realize it is Remdesivir by default as specified long ago above)

**Comment by jburel** [comment]
> Problem with Compound name display in the Filter by compound cell
> Numbers discplayed only
> Screenshot 2021-05-24 at 11 18 55

What is the problem?
I sort the table according to the concentration. So the number is "before" the sorting

**Comment by pwalczysko** [comment]
> I sort the table according to the concentration. So the number is "before" the sorting

That is fine. But the general overview is not there, I mean.

1. What is the "number" ? (that column could have a header)
2. The concentration and inhibition columns have no units.
3. What is the "dbl" under each header ?

**Comment by jburel** [comment]
This is a simpler table so we can manipulate
We probably do not need to print it.

**Comment by jburel** [comment]
@dominikl @pwalczysko 
Last set of commits
* Sort the compounds in the shiny app
* Improve the display of the thumbnails in ic50 notebook
* Add display of thumbnails in ic50_loadtable notebook

**Comment by pwalczysko** [comment]
All improvements work as expected. Ready to merge fmpov.

**Pull request merged**
